# Generated by Django 5.0.7 on 2024-08-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0005_post_image_post_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
