# Generated by Django 5.0.7 on 2024-08-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default='3'),
            preserve_default=False,
        ),
    ]
